clusterId: cl3795l6o
command: nvidia-smi && pip install tensorflow && pip3 install torch==1.6.0 -f https://download.pytorch.org/whl/cu101/torch_stable.html && python gradient_train.py
container: paperspace/gradient-walkthrough:gpt2
experimentEnv:
    steps: 500
machineType: V100
modelPath: /artifacts
modelType: Custom
name: gpt-train
projectId: pr2l8tlk8
workingDirectory: null
workspace: ./
ignoreFiles: trained_model/*,notebooks/*,build/*,dist/*,aitextgen.egg-info/*
workspacePassword: null
workspaceRef: null
workspaceUsername: null
